#!/bin/bash
#Test script to see if the update works all the time

COUNT=1
while true
do
	./test_bcm8544 $COUNT "  $COUNT" "    $COUNT" "      $COUNT" "        $COUNT" "          $COUNT"
	COUNT=$((COUNT+1))
	sleep 1
done

