#!/bin/bash

while true
do
	UPTIME=`uptime | awk -F'( |,|:)+' '{if ($7=="min") m=$6; else {if ($7~/^day/) {d=$6;h=$8;m=$9} else {h=$6;m=$7}}} {print d+0,"d",h+0,":",m+0}'`
	FREERAM=`awk '/MemAvailable/ { printf "%.3f \n", $2/1024 }' /proc/meminfo`
	IPADDRESS=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'`
	DISKUSE=`df -m / | tail -1 | awk '{ print $5; }'`
	TEMPERATURE=`/opt/vc/bin/vcgencmd measure_temp`
	TIME=`date "+%d-%m-%y %H:%M"`
	./test_bcm8544 "$TIME" $TEMPERATURE "ram $FREERAM" "disk $DISKUSE" "$UPTIME" $IPADDRESS
	sleep 20
done

